TARGETNAME 	= 	quopter
MODULES    	= 	quopter quadctrl
FWMODULES   =  pid i2cmast mpu6050 pwmbang
DEVICE     	= 	atmega328p
PARAMETERS	= 	F_CPU=16000000																\
					I2C_FREQUENCY=400000														\
					I2C_BUFFER_SIZE=16														\
					PWMBANG_CHANNEL_COUNT=4													\
					PWMBANG_SERVO

include ../fw/base.mak
