TARGETNAME 	= 	quopter
MODULES    	= 	quopter quadctrl
FWMODULES   =  pid tlc5940 i2cmast
DEVICE     	= 	atmega328p
PARAMETERS	= 	F_CPU=16000000																\
					TLC5940_COUNT=1															\
					I2C_FREQUENCY=400000														\
					I2C_BUFFER_SIZE=16

include ../fw/base.mak
