TARGETNAME 	= 	wiichuk
MODULES    	= 	wiichuk
FWMODULES	=  i2cmast spimast nrf24
DEVICE     	= 	atmega328p
PARAMETERS	= 	F_CPU=16000000 															\
					SPI_BUFFER_SIZE=13														\
				 	SPI_FREQUENCY=8000000													\
					I2C_FREQUENCY=100000														\
				 	I2C_BUFFER_SIZE=6

include ../fw/base.mak
