TARGETNAME 	= 	lab
MODULES    	= 	lab
FWMODULES   =	uart i2cmast mpu6050 tlc5940
DEVICE     	= 	atmega328p
PARAMETERS	= 	F_CPU=16000000																\
					DEBUG_TRACE=UartTrace													\
					UART_BAUD=57600															\
					UART_BAUD_2X=0																\
					UART_SEND=1																	\
					UART_RECV=1																	\
					TLC5940_FREQ=390.625														\
					TLC5940_BLSCALE=256														\
					TLC5940_BLTICK=1															\



include ../fw/base.mak
