TARGETNAME 	= 	avrlab
MODULES    	= 	avrlab
FWMODULES   =	uart
DEVICE     	= 	atmega328p
PARAMETERS	= 	F_CPU=16000000																\
					DEBUG_TRACE=UartTrace													\
					UART_BAUD=57600															\
					UART_BAUD_2X=0																\
					UART_SEND=1

include ../fw/base.mak
