TARGETNAME  = 	locomoto
MODULES     = 	proto stepper locomoto
FWMODULES   =  uart shiftreg
DEVICE      = 	atmega328p
PARAMETERS	= 	F_CPU=16000000 															\
				 	UART_SEND=1																	\
				 	UART_RECV=1																	\
				 	UART_RECV_BUFFER_SIZE=16												\
				 	SHIFTREG_SIZE=3

include ../fw/base.mak
