TARGETNAME  = 	locomoto
MODULES     = 	stepper locopsx locomoto
FWMODULES   =  pid spimast shiftreg nrf24
DEVICE      = 	atmega328p
PARAMETERS	= 	F_CPU=16000000 															\
				 	SHIFTREG_SIZE=2															\
					SPI_BUFFER_SIZE=33														\
				 	SPI_FREQUENCY=8000000													\
				 	LOCOPSX_ADDRESS=\"Psx00\"

include ../fw/base.mak
