TARGETNAME 	= 	uartpong
MODULES    	= 	uartpong
FWMODULES   =	uart
DEVICE     	= 	atmega328p
PARAMETERS	= 	F_CPU=16000000																\
					UART_BAUD=57600															\
					UART_BAUD_2X=0																\
					UART_SEND=1																	\
					UART_RECV=1

include ../fw/base.mak
