TARGETNAME 	= 	psxpad
MODULES    	= 	psxpad
FWMODULES   =	spimast nrf24
DEVICE     	= 	atmega328p
PARAMETERS	= 	F_CPU=16000000																\
					SPI_BUFFER_SIZE=33														\
				 	SPI_FREQUENCY=8000000

include ../fw/base.mak
